# Hugging Face Spaces configuration
sdk: gradio
sdk_version: 4.44.1
app_file: app.py
pinned: false
license: mit
colorFrom: blue
colorTo: purple
emoji: 📸
title: SQRT - Selfie Quality Rater
short_description: AI-powered selfie analysis with real-time feedback

